### ISSUE TITLE
konashiをI2C slaveとして利用したい

### ISSUE THREAD

**Issue by tichise** [YUKAI/konashi-ios-sdk#107]
[こちら](http://konashi.ux-xu.com/documents/)のドキュメントに 
> konashi は、I2Cのマスタとして動作し、接続された周辺機器（スレーブ）と通信をおこないます。

と書かれてるのですが、konashiをslaveとして利用することは可能でしょうか？

現在はkonashi （master）と mbed（slave）をiOSアプリと繋げて使ってるのですが、その方法だとiOSアプリ側からi2cReadRequestがないとアプリ側でデータを受信できません。 

mbedに温度センサーを繋げてその数値が変わった時にそれをトリガーにして、iOSアプリ側の情報を更新するといった使い方をしたいです。

**Comment by sagiii** [comment]
konashi, konashi2.0, ともにi2c masterのみ対応しております。
konashi2.0についてはファームウェアをアップデート可能ですが、チップの制約でmasterとしてのみ動作可能です。データシート `20737-DS100-R.pdf` の対応する部分のスクリーンショットを掲載いたします：

<img width="1392" alt="2017-01-25 22 07 17" src="https://cloud.githubusercontent.com/assets/3139682/22291621/ab90e2b6-e34a-11e6-877b-237f755d4d63.png">

**Comment by tichise** [comment]
@sagiii レスありがとうございます。
