### ISSUE TITLE
LED2点灯サンプル、点灯しない事象について

### ISSUE THREAD

**Issue by Kuro-cats** [YUKAI/konashi-ios-sdk#64]
Getting Startedのプログラムを元にkonashiについているLED2を点灯させようとしたのですが、点灯しません。
bluetooth によるiPhone(5c)との接続は、完了しているみたいです。（ログ出力により、確認）

**Comment by 0x0c** [comment]
@Kuro-cats 様
返信遅れて申し訳ありません。
-pinMode:mode:は正しく設定されていますでしょうか？
LEDを点灯させるにはmodeをKonashiPinModeOutputにする必要があります。

サンプルの改修が間に合っておらず申し訳ありません。
疑問点などございましたら、遠慮なく申し付けください。

よろしくお願いいたします。

**Comment by tarotaro** [comment]
自分も、PioDriveのサンプルでためしたのですが、Inputは取れるようですが、
Output側が動いてないように思います。
自分で作ったプログラムでも、KonashiDigitalIO1のmodeをKonashiPinModeOutputにして
やってみたのですが、値が出力されなく、LEDが点灯しません
こちらも、KonashiDigitalIO0をIputモードにして実行してみたら値はとれました、
全体的にOutputが動いてないようです。
環境はiOS8.4  Xcode6.4です
確認お願いします。

**Comment by sagiii** [comment]
@Kuro-cats 様、 @tarotaro 様、
#66
に記載の別のissueと切り分けたいのですが、アプリ起動後わざと一回konashiの電源を抜き、再度開きっぱなしの同じアプリからconnectしてpioをいじるとどうなりますでしょうか？

**Comment by tarotaro** [comment]
起動したあとに、コネクトしないで、上記操作をするとLEDは特に変わらず点灯しませんでした、
コネクトしたあと、konashiの電源を抜き再度開きっぱなしのアプリからコネクトしてpioをいじると
LEDは点灯しました、つまりアプリからも、HWについてるスイッチをいじってもLEDは点灯しました。

**Comment by sagiii** [comment]
@tarotaro 様
ご報告ありがとうございます。
#66
と同根の可能性が高そうですので、バグフィックス優先度高めに進めます。
 2015/07/24 1:09 "tarotaro" <notifications@github.com>:

**Comment by sagiii** [comment]
@Kuro-cats @tarotaro
https://github.com/YUKAI/konashi-ios-sdk/releases/tag/v4.0.0
こちらのリリースにて、本件のbug fixを完了いたしました。
ご確認いただけますと幸いです。
なお、インタフェース仕様の変更が必要になってしまいましたため、メジャーバージョンアップをさせていただいております。イベントハンドラ周りについて、従来のユーザコードは使えなくなる可能性がありますので、Konashi.xcworkspace内包のサンプルコードをご参照ください。

**Comment by tarotaro** [comment]
修正ありがとうございました
