### ISSUE TITLE
"findWithName"が使えないです。

### ISSUE THREAD

**Issue by naogify** [YUKAI/konashi-ios-sdk#65]
初めまして、

"findWithName"についての質問です。
アプリの立ち上げ時に指定のkonashiに接続する機能を、”findWithName”を使い実装を試みました。
しかし”find”の実行時と同じく接続先リストが表示されます。
```
if ([Konashi findWithName:@"konashi2-f014a6"] == KonashiResultSuccess) {

       NSLog(@"findWithName is true!"); 

    }else{

        [Konashi find];

        NSLog(@"findWithName is false!");

}
```

上記のコードをviewDidLoadに記述、デバッグ結果は「findWithName is true!」ですが、実行結果は変わらず接続先リストが表示されます。これはバグでしょうか？それとも書き方が悪いのでしょうか？ご教授よろしくお願いします。

**Comment by sagiii** [comment]
@naogify 

ご不便をおかけして申し訳ございません。
こちらの現象ですが、手元で最新のkonashi-ios-sdkにて再現いたしましたので、
sdkのバグと考えられます。

より詳細には、アプリ起動直後の１回目のfindWithName時には再現し、2回目のfindWithName時には成功するという現象でした。
#64 や #66 と関係がありそうです。
優先度高めでバグフィックス対応をさせていただきます。

**Comment by 0x0c** [comment]
@naogify @sagiii 
一つ補足させていただきますと、-findWithName:の戻り値は接続が成功したことではなく、メソッドが正しく実行されたことを意味しております。
そのため、Konashiクラスを用いてすでに接続している場合以外はKonashiResultSuccessがreturnされます。

**Comment by sagiii** [comment]
@naogify
https://github.com/YUKAI/konashi-ios-sdk/releases/tag/v4.0.0
こちらのリリースにて、本件のbug fixを完了いたしました。
ご確認いただけますと幸いです。
なお、インタフェース仕様の変更が必要になってしまいましたため、メジャーバージョンアップをさせていただいております。イベントハンドラ周りについて、従来のユーザコードは使えなくなる可能性がありますので、Konashi.xcworkspace内包のサンプルコードをご参照ください。

**Comment by naogify** [comment]
@sagiii @0x0c 返信遅れて申し訳ありません。ご回答ありがとうございます。
URLのサンプルコードの方参考にさせて頂きます！
