### ISSUE TITLE
UartSampleのwriteDataの引数がまちがっている

### ISSUE THREAD

**Issue by sagiii** [YUKAI/konashi-ios-sdk#81]
1
を与えているが、
uint8_t arr = 1;
[NSData dataWithBytes:*arr]
などに修正が必要

**Comment by 0x0c** [comment]
warningが出るのは-uartWrite:がdeprecatedになったためです。
-uartWriteData:を使えばおｋです。

**Comment by sagiii** [comment]
どっちかいうと、
-uartWriteData
なのに、わたしているのはNSDataじゃなくてcharっていう問題です。

2015-09-25 17:31 GMT+09:00 Akira MATSUDA <notifications@github.com>:

> warningが出るのは-uartWrite:がdeprecatedになったためです。
> -uartWriteData:を使えばおｋです。
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/YUKAI/konashi-ios-sdk/issues/81#issuecomment-143160356>
> .
>



-- 
鷺坂 隆志
SAGISAKA Takashi
sagisaka@ux-xu.com
090-5769-0963

ユカイ工学株式会社
http://www.ux-xu.com/

東京都新宿区富久町16-11 武蔵屋スカイビル101号
http://goo.gl/maps/tuv8z

TEL:03-6380-4710

【新製品】BOCCO 〜 家族をつなぐコミュニケーションロボット 〜
http://youtu.be/qiWEhdBeQmA

**Comment by 0x0c** [comment]
具体的にどの行か教えていただけますか？

**Comment by sagiii** [comment]
失礼しました。サンプルコードは大丈夫でした。
