### ISSUE TITLE
Parse & Semantic issue at CBPeripheral+Konashi.m

### ISSUE THREAD

**Issue by kugehajime** [YUKAI/konashi-ios-sdk#89]
<h3>Build information, specifically the full version.</h3>
- X code V-6.4
- konashi-ios-sdk-4.0.2

<h3>Steps to reproduce</h3>
1. download zip from repo `konashi-ios-sdk`
2. build sample projects from `Konashi.xcworkspace`
3. return error msg
* konashi-ios-sdk-4.0.2/Konashi/Konashi/Category/CoreBluetooth/CBPeripheral+Konashi.m:33:67: Expected ')'
* konashi-ios-sdk-4.0.2/Konashi/Konashi/Category/CoreBluetooth/CBPeripheral+Konashi.m:35:48: Use of undeclared identifier 's'
* konashi-ios-sdk-4.0.2/Konashi/Konashi/Category/CoreBluetooth/CBPeripheral+Konashi.m:33:44: Incompatible block pointer types sending 'void (^)(CBService *__strong)' to parameter of type 'void (^)(__strong id, NSUInteger, BOOL *)'

![2015-10-15 00 49 11](https://cloud.githubusercontent.com/assets/1793052/10490087/297b5dc4-72da-11e5-9e58-57b8bd5ce41a.png)

<h3>Expected results</h3>
build success
<h3>Actual results</h3>
fail
<h3>Approximate probability</h3>
100%

**Comment by sagiii** [comment]
This is caused by the code is written including new features introduced in xcode7.
@kugehajime 
The first and fastest aid for you might be, use xcode7 to build.

We're now discussing whether and how fast we have to fix this issue for xcode6 users.

Best.

**Comment by sagiii** [comment]
move onto #90

**Comment by kugehajime** [comment]
@sagiii thx for your reply. gotcha :-)

**Comment by 0x0c** [comment]
I fixed this issue at feature/old_objective_c branch.
If you want to use konashi-ios-sdk with Xcode6 immediately, please use this branch.

Regards ;)
